TourneySeeds <- read.csv("../TourneySeeds.csv")
SampleSubmission <- read.csv("../SampleSubmission.csv")
Seasons <- read.csv("../Seasons.csv")
Teams <- read.csv("../Teams.csv")
TourneySlots <- read.csv("../TourneySlots.csv")
TourneyDetailedResults <- read.csv("../TourneyDetailedResults.csv")
TourneyCompactResults <- read.csv("../TourneyCompactResults.csv")